CREATE DATABASE meta_land_1NF;
use meta_land_1NF;

CREATE TABLE Kullanicilar (
    KullaniciNo INT PRIMARY KEY,
    KullaniciAdi VARCHAR(255),
    KullaniciSoyadi VARCHAR(255),
    KullaniciSifresi VARCHAR(255),
    KullaniciYemekMiktari DECIMAL(10,2),
    KullaniciEsyaMiktari DECIMAL(10,2),
    KullaniciParaMiktari DECIMAL(10,2),
    BaslangicYemekMiktari DECIMAL(10,2),
    BaslangicEsyaMiktari DECIMAL(10,2),
    BaslangicParaMiktari DECIMAL(10,2),
    OyunBaslangicTarihi DATE,
    OyunAlanBoyutu VARCHAR(10),
    AlanNo INT,
    AlanTuru VARCHAR(10),
    AlanSahibi VARCHAR(255),
    GunlukYiyecekGideri DECIMAL(10,2),
    GunlukEsyaGideri DECIMAL(10,2),
    GunlukParaGideri DECIMAL(10,2),
    IsletmeTuru VARCHAR(10),
    YoneticiIsletmeUcreti DECIMAL(10,2),
    KullaniciIsletmeUcreti DECIMAL(10,2),
    KullaniciCalismaBaslangicTarihi DATE,
    KullaniciCalismaBitisTarihi DATE,
    KullaniciCalismaGunSayisi INT,
    KullaniciCalismaSaatleri VARCHAR(255),
    IsletmeSeviyesi INT,
    IsletmeKapasitesi INT,
    IsletmeCalisanSayisi INT,
    MarketYiyecekUcreti DECIMAL(10,2),
    MagazaEsyaUcreti DECIMAL(10,2),
    IsletmeFiyati DECIMAL(10,2),
    KiralikIsletmeFiyati DECIMAL(10,2),
    EmlakKomisyonu DECIMAL(10,2),
    EmlakIslemi VARCHAR(10),
    KiraSure INT,
    SatisTarihi DATE,
    KiralamaTarihi DATE,
    KiraBitisTarihi DATE,
    IslemYapilanEmlak VARCHAR(255),
    IsletmeSabitGelirMiktari DECIMAL(10,2),
    IsletmeSabitGelirOrani DECIMAL(5,2),
    IsletmeMevcutSeviyeBaslangicTarihi DATE
);
